version: '3'
services:
    node:
        image: registry.thinknet.co.th/sredev/node:10.15
        command: ["/bin/sh", "-c", "yarn && yarn dev"]
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
networks:
    default:
        external:
            name: microservicenetwork