version: '3.1'
services:
### Local Mongo
    mongodb:
        image: mongo
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017

networks:
    default:
        external:
            name: microservicenetwork